channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=1_llvm
- ads=0.12.3=py_2
- afterimage=1.21=ha9998ff_1003
- amqp=2.6.1=pyh9f0ad1d_0
- apipkg=1.5=py_0
- appdirs=1.4.4=pyh9f0ad1d_0
- astroid=2.3.3=py38_1
- astroplan=0.6=py_1
- astropy-healpix=0.5=py38h0b5ebd8_1
- astropy=4.0=py38h1e0a361_2
- atk-1.0=2.36.0=h3371d22_4
- attrs=20.3.0=pyhd3deb0d_0
- autoconf=2.69=pl5320h36c2ea0_10
- automake=1.16.1=pl5320ha770c72_1004
- automat=20.2.0=py_0
- awkward=0.15.0=pyhd3deb0d_0
- backcall=0.2.0=pyh9f0ad1d_0
- backports.functools_lru_cache=1.6.1=py_0
- backports=1.0=py_2
- bayeswave=1.0.6=h7d508c1_1
- bayeswaveutils=1.0.6=py38h578d9bd_1
- bc=1.07.1=h516909a_0
- bcrypt=3.2.0=py38h497a2fe_1
- beautifulsoup4=4.9.0=py38h32f6830_0
- bilby=1.0.4=pyhd8ed1ab_0
- bilby_pipe=1.0.2=py_0
- billiard=3.6.3.0=py38h497a2fe_3
- binutils=2.35.1=hdd6e379_2
- binutils_impl_linux-64=2.35.1=h193b22a_2
- binutils_linux-64=2.35=h67ddf6f_30
- black=19.10b0=py_4
- bleach=3.3.0=pyh44b312d_0
- blosc=1.21.0=h9c3ff4c_0
- boost-cpp=1.74.0=hc6e9bd1_2
- boost=1.74.0=py38hc10631b_3
- boto=2.49.0=py_0
- bottle=0.12.18=py_0
- bruco=0.1.4=py38h578d9bd_0
- bzip2=1.0.8=h7f98852_4
- c-ares=1.17.1=h7f98852_1
- c-compiler=1.1.3=h7f98852_0
- ca-certificates=2020.12.5=ha878542_0
- cachetools=4.2.1=pyhd8ed1ab_0
- cairo=1.16.0=h7979940_1007
- cdsutils=1.4.1=pyh9f0ad1d_0
- celery-eternal=0.1.1=py_0
- celery-singleton=0.1.3=py_1
- celery=4.4.6=pyh9f0ad1d_0
- certifi=2020.12.5=py38h578d9bd_1
- cffi=1.14.5=py38ha65f79e_0
- cfitsio=3.470=hb418390_7
- chardet=3.0.4=py38h924ce5b_1008
- chealpix=3.31.0=h60f8253_0
- ciecplib=0.4.1=py_0
- click-didyoumean=0.0.3=pyh8c360ce_0
- click=7.1.1=pyh8c360ce_0
- cloudpickle=1.6.0=py_0
- cmake=3.15.5=hf94ab9c_0
- colorama=0.4.4=pyh9f0ad1d_0
- coloredlogs=14.0=py38h32f6830_2
- comet=3.1.0=py_0
- compilers=1.1.3=ha770c72_0
- configargparse=1.3=pyhd8ed1ab_0
- configobj=5.0.6=py_0
- constantly=15.1.0=py_0
- coreutils=8.31=h516909a_0
- corner=2.0.1=py_1003
- cryptography=3.3.1=py38h2b97feb_1
- curl=7.71.1=he644dc0_8
- cwinpy=0.2.1=py_0
- cxx-compiler=1.1.3=h4bd325d_0
- cycler=0.10.0=py_2
- cyrus-sasl=2.1.27=h3274739_1
- cython=0.29.16=py38h950e882_0
- davix=0.7.6=hb44b51d_0
- dbus-python=1.2.16=py38hec75210_2
- dbus=1.13.6=hfdff14a_1
- decorator=4.4.2=py_0
- deepdish=0.3.4=py_3
- defusedxml=0.7.1=pyhd8ed1ab_0
- dill=0.3.1.1=py38h32f6830_1
- dnspython=1.16.0=py_1
- dqsegdb2=1.0.1=py_0
- dqsegdb=1.6.1=py38_0
- dynesty=1.0.1=py_1
- ecdsa=0.16.1=pyhd8ed1ab_0
- emcee=2.2.1=pyh24bf2e0_4
- entrypoints=0.3=pyhd8ed1ab_1003
- epics-base=7.0.3.1=h68659b9_2
- execnet=1.8.0=pyh44b312d_0
- expat=2.2.10=h9c3ff4c_0
- ezca=1.4.0=py_0
- fftw=3.3.9=nompi_h74d3f13_101
- flake8=3.7.9=py38h32f6830_1
- flask-cache=0.13.1=py_1000
- flask-sqlalchemy=2.4.0=py_0
- flask=0.12.4=py_0
- flex=2.6.4=h58526e2_1004
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- font-ttf-inconsolata=2.001=hab24e00_0
- font-ttf-source-code-pro=2.030=hab24e00_0
- font-ttf-ubuntu=0.83=hab24e00_0
- fontconfig=2.13.1=hba837de_1004
- fonts-conda-ecosystem=1=0
- fonts-conda-forge=1=0
- fortran-compiler=1.1.3=h1990efc_0
- framel=8.41.1=h7f98852_0
- freetype=2.10.4=h0708190_1
- freezegun=0.3.15=py_0
- fribidi=1.0.10=h36c2ea0_0
- ftgl=2.4.0=hbcb1f35_0
- future=0.18.2=py38h578d9bd_3
- gcc_impl_linux-64=9.3.0=h70c0ae5_18
- gcc_linux-64=9.3.0=hf25ea35_30
- gct=6.2.1550507116=h8cfc5f6_2
- gdk-pixbuf=2.42.2=h0c95a7a_2
- geos=3.7.2=he1b5a44_2
- gettext=0.19.8.1=h0b5b191_1005
- gfortran_impl_linux-64=9.3.0=hc4a2995_18
- gfortran_linux-64=9.3.0=hdc58fab_30
- giflib=5.2.1=h36c2ea0_2
- git-lfs=2.10.0=0
- git=2.26.0=pl526hf241897_0
- gitdb=4.0.5=pyhd8ed1ab_1
- gitpython=3.1.1=py_0
- gl2ps=1.4.2=h0708190_0
- glew=2.1.0=h9c3ff4c_2
- glib-tools=2.66.7=h9c3ff4c_1
- glib=2.66.7=h9c3ff4c_1
- gmp=6.2.1=h58526e2_0
- gobject-introspection=1.66.1=py38h951ac0e_4
- gpstime=0.4.4=py38h32f6830_2
- gracedb-sdk=0.1.6=py_0
- graphite2=1.3.13=h58526e2_1001
- graphviz=2.46.1=h93c640b_4
- gsl=2.6=he838d99_2
- gst-plugins-base=1.18.3=h04508c2_0
- gstreamer=1.18.3=h3560a44_0
- gtk2=2.24.33=hab0c2f8_0
- gts=0.7.6=h64030ff_2
- guardian=1.4.1=py38h32f6830_1
- gwdatafind=1.0.4=py_0
- gwdetchar=2.0.3=pyhd8ed1ab_0
- gwinc=0.2.2=pyhd8ed1ab_0
- gwollum=2.4.2=h735fe92_0
- gwosc=0.5.4=py_0
- gwpy=2.0.2=pyhd8ed1ab_0
- gwsumm=2.0.1=pyhd8ed1ab_0
- gwsurrogate=1.0.1=py38ha777a67_1
- gwtools=1.0.6=pyh9f0ad1d_0
- gwtrigfind=0.8.0=py_0
- gxx_impl_linux-64=9.3.0=hd87eabc_18
- gxx_linux-64=9.3.0=h3fbe746_30
- h5py=2.10.0=nompi_py38h7442b35_105
- halo=0.0.31=pyhd8ed1ab_0
- harfbuzz=2.7.4=h5cf4720_0
- hdf5=1.10.6=nompi_h6a2412b_1114
- healpy=1.14.0=py38hcad0ea4_2
- htchirp=2.0=pyh9f0ad1d_0
- htcondor-classads=8.9.11=hd3c618e_2
- htmap=0.6.1=pyhd8ed1ab_1
- humanfriendly=9.1=py38h578d9bd_0
- humanize=0.5.1=py_1
- hveto=2.0.1=pyhd8ed1ab_0
- hyperlink=21.0.0=pyhd3deb0d_0
- icu=68.1=h58526e2_0
- idna=2.10=pyh9f0ad1d_0
- idq=0.3.1=py38h32f6830_2
- igwn-cmake=1.2.1=0
- importlib-metadata=3.7.2=py38h578d9bd_0
- incremental=17.5.0=py_0
- inspiral-range=0.6.0=py38h578d9bd_0
- ipykernel=5.2.0=py38h23f93f0_1
- ipyparallel=6.3.0=py38h578d9bd_2
- ipython=7.13.0=py38h32f6830_2
- ipython_genutils=0.2.0=py_1
- isort=4.3.21=py38h32f6830_1
- itsdangerous=1.1.0=py_0
- jedi=0.17.2=py38h578d9bd_1
- jinja2=2.11.2=pyh9f0ad1d_0
- joblib=1.0.1=pyhd8ed1ab_0
- jpeg=9d=h36c2ea0_0
- jsonschema=3.2.0=pyhd8ed1ab_3
- jupyter_client=6.1.3=py_0
- jupyter_console=6.1.0=py_1
- jupyter_core=4.6.3=py38h578d9bd_2
- kernel-headers_linux-64=2.6.32=h77966d4_13
- kiwisolver=1.3.1=py38h1fd1430_1
- kombine=0.8.4=py_0
- kombu=4.6.11=py38h32f6830_0
- krb5=1.17.1=hfafb76e_3
- lal=7.1.2=fftw_py38hd1b70e9_100
- lalapps=7.2.0=py38h0b658a1_0
- lalburst=1.5.8=py38h497a2fe_0
- lalframe=1.5.4=py38h497a2fe_0
- lalinference=2.0.7=mpi_openmpi_py38haaa2f6c_0
- lalinspiral=2.0.2=py38h497a2fe_0
- lalmetaio=2.0.2=py38h497a2fe_0
- lalpulsar=3.0.1=py38h497a2fe_0
- lalsimulation=2.5.1=py38h434642f_0
- lalsuite=6.82=pyhd8ed1ab_0
- lazy-object-proxy=1.5.2=py38h497a2fe_1
- lcms2=2.12=hddcbb42_0
- ld_impl_linux-64=2.35.1=hea4e1c9_2
- ldas-tools-al=2.6.4=hf7ed750_3
- ldas-tools-cmake=1.2.1=he1b5a44_0
- ldas-tools-diskcacheapi-swig=2.6.8=hc9558a2_0
- ldas-tools-diskcacheapi=2.7.0=h8b68381_0
- ldas-tools-filters=2.6.4=hc9558a2_0
- ldas-tools-frameapi-swig=2.6.8=hc9558a2_0
- ldas-tools-frameapi=2.6.4=he9ae1f9_0
- ldas-tools-framecpp-swig=2.6.9=he1b5a44_2
- ldas-tools-framecpp=2.7.0=hc145dac_4
- ldas-tools-ldasgen-swig=2.6.7=hc9558a2_2
- ldas-tools-ldasgen=2.7.0=h11112f5_1
- libblas=3.8.0=17_openblas
- libcblas=3.8.0=17_openblas
- libclang=11.1.0=default_ha53f305_0
- libcondor_utils=8.9.11=h722fe0d_2
- libcurl=7.71.1=hcdd3856_8
- libcxx=11.1.0=h4bd325d_0
- libcxxabi=11.1.0=ha770c72_0
- libdaemon=0.14=h516909a_0
- libedit=3.1.20191231=he28a2e2_2
- libev=4.33=h516909a_1
- libevent=2.1.10=hcdb4288_3
- libffi=3.3=h58526e2_2
- libframel=8.41.1=h7f98852_0
- libgcc-devel_linux-64=9.3.0=h7864c58_18
- libgcc-ng=9.3.0=h2828fa1_18
- libgcrypt=1.9.2=h7f98852_0
- libgd=2.3.0=h47910db_1
- libgfortran-ng=9.3.0=hff62375_18
- libgfortran5=9.3.0=hff62375_18
- libglib=2.66.7=h3e27bee_1
- libglu=9.0.0=he1b5a44_1001
- libgomp=9.3.0=h2828fa1_18
- libgpg-error=1.41=h9c3ff4c_0
- libgsasl=1.8.0=2
- libiconv=1.16=h516909a_0
- libidn2=2.3.0=h516909a_0
- liblal=7.1.2=fftw_ha6096f8_100
- liblalburst=1.5.8=h8832763_0
- liblalframe=1.5.4=h7f98852_0
- liblalinference=2.0.7=h8832763_0
- liblalinspiral=2.0.2=h8832763_0
- liblalmetaio=2.0.2=h7f98852_0
- liblalpulsar=3.0.1=hf71512e_0
- liblalsimulation=2.5.1=h8832763_0
- liblapack=3.8.0=17_openblas
- liblapacke=3.8.0=17_openblas
- libllvm11=11.1.0=hf817b99_0
- libllvm8=8.0.1=hc9558a2_0
- libnghttp2=1.43.0=h812cca2_0
- libntlm=1.4=h7f98852_1002
- libopenblas=0.3.10=pthreads_h4812303_5
- libpng=1.6.37=h21135ba_2
- libpq=13.1=hfd2b0eb_2
- librdkafka=1.5.3=hc49e61c_1
- librsvg=2.50.3=hfa39831_1
- libsodium=1.0.18=h36c2ea0_1
- libssh2=1.9.0=ha56f1ee_6
- libstdcxx-devel_linux-64=9.3.0=hb016644_18
- libstdcxx-ng=9.3.0=h6de172a_18
- libtiff=4.2.0=hdc55705_0
- libtool=2.4.6=h58526e2_1007
- libunistring=0.9.10=h14c3975_0
- libuuid=2.32.1=h7f98852_1000
- libuv=1.41.0=h7f98852_0
- libwebp-base=1.2.0=h7f98852_0
- libwebp=1.2.0=h3452ae3_0
- libxcb=1.13=h7f98852_1003
- libxkbcommon=1.0.3=he3ba5ed_0
- libxml2=2.9.10=h72842e0_3
- libxslt=1.1.33=h15afd5d_2
- ligo-common=1.0.4=py_0
- ligo-followup-advocate=1.1.8=py_0
- ligo-gracedb=2.7.6=pyhd8ed1ab_0
- ligo-lvalert=1.5.6=py38_0
- ligo-proxy-utils=2.0.0=pyhd8ed1ab_0
- ligo-raven=1.18=py38h578d9bd_1
- ligo-scald=0.7.2=py_0
- ligo-segments=1.3.0=py38h497a2fe_1
- ligo.skymap=0.5.0=py38h2002d8b_0
- ligotimegps=2.0.0=py_0
- lintegrate=0.1.7=py38h55b2093_0
- llvm-openmp=11.0.1=h4bd325d_0
- llvmlite=0.31.0=py38h4f45e52_1
- log_symbols=0.0.14=pyh8c360ce_0
- lscsoft-glue=2.0.0=py38h516909a_1
- lxml=4.5.0=py38hbb43d70_1
- lz4-c=1.9.3=h9c3ff4c_0
- lz4=3.1.3=py38hebdc3cf_0
- lzo=2.10=h516909a_1000
- m2crypto=0.35.2=py38h72c5cf5_0
- m4=1.4.18=h516909a_1001
- make=4.2.1=h14c3975_2004
- mako=1.1.4=pyh44b312d_0
- markdown=3.3.4=pyhd8ed1ab_0
- markuppy=1.14=py_0
- markupsafe=1.1.1=py38h497a2fe_3
- matplotlib-base=3.3.2=py38h5c7f4ab_1
- matplotlib=3.3.2=py38h578d9bd_1
- mccabe=0.6.1=py_1
- metaio=8.5.1=h84994c4_1000
- metakernel=0.27.5=pyhd3deb0d_0
- mistune=0.8.4=py38h497a2fe_1003
- mkl=2020.1=219
- mock=4.0.3=py38h578d9bd_1
- more-itertools=8.7.0=pyhd8ed1ab_0
- mpi=1.0=openmpi
- mpld3=0.3=py_2
- munge=0.5.13=h1a52d62_0
- mysql-common=8.0.23=ha770c72_1
- mysql-libs=8.0.23=h935591d_1
- nbconvert=5.6.1=py38h32f6830_1
- nbformat=5.1.2
- ncurses=6.2=h58526e2_4
- nds2-client=0.16.6=hd02d5f2_0
- ndscope=0.7.9=py_1
- networkx=2.5=py_0
- notebook=6.0.3=py38h32f6830_1
- nspr=4.29=h9c3ff4c_1
- nss=3.62=hb5efdd6_0
- numba=0.47.0=py38hb3f55d8_0
- numexpr=2.7.3=py38h51da96c_0
- numpy=1.19.5=py38h18fd61f_1
- olefile=0.46=pyh9f0ad1d_1
- omicron=2.4.2=hb008238_0
- openmpi=4.1.0=hbfc84c5_2
- openssl=1.1.1j=h7f98852_0
- p_astro=0.8.2=py_0
- packaging=20.9=pyh44b312d_0
- pamela=1.0.0=py_0
- pandas=0.25.3=py38hb3f55d8_0
- pandoc=2.7.3=0
- pandocfilters=1.4.2=py_1
- pango=1.42.4=h69149e4_5
- parso=0.7.1=pyh9f0ad1d_0
- pathspec=0.8.1=pyhd3deb0d_0
- patsy=0.5.1=py_0
- pcaspy=0.7.2=py38hc5bc63f_1
- pcre=8.44=he1b5a44_0
- pepredicates=0.0.3=py_0
- perl=5.26.2=h36c2ea0_1008
- pesummary=0.11.0=pyhd8ed1ab_1
- pexpect=4.8.0=pyh9f0ad1d_2
- pickleshare=0.7.5=py_1003
- pillow=8.1.2=py38ha0e1e83_0
- pip=20.0.2=py_2
- pixman=0.40.0=h36c2ea0_0
- pkg-config=0.29.2=h36c2ea0_1008
- plotly=4.14.3=pyh44b312d_0
- pluggy=0.13.1=py38h578d9bd_4
- portalocker=1.7.0=py38h578d9bd_1
- prometheus_client=0.9.0=pyhd3deb0d_0
- prompt-toolkit=3.0.16=pyha770c72_0
- prompt_toolkit=3.0.16=hd8ed1ab_0
- psrqpy=1.0.11=pyh9f0ad1d_0
- psycopg2=2.8.6=py38h497a2fe_2
- ptemcee=1.0.0=py_0
- pthread-stubs=0.4=h36c2ea0_1001
- ptyprocess=0.7.0=pyhd3deb0d_0
- py=1.8.1=py_0
- pyasn1-modules=0.2.7=py_0
- pyasn1=0.4.8=py_0
- pycairo=1.20.0=py38h323dad1_1
- pycbc=1.18.0=py38h4c3c19e_0
- pycodestyle=2.5.0=py_0
- pycondor=0.5.0=py_1
- pycparser=2.20=pyh9f0ad1d_2
- pycryptodome=3.10.1=py38h80e8405_0
- pydotplus=2.0.2=pyhd1c1de3_3
- pyepics=3.4.1=py38h32f6830_2
- pyflakes=2.1.0=py_0
- pygcn=1.0.2=py_0
- pygments=2.7.3=pyhd8ed1ab_0
- pygobject=3.38.0=py38h073a499_4
- pyhamcrest=2.0.2=py_0
- pykerberos=1.2.1=py38he0378a5_4
- pylint=2.4.4=py38_0
- pyomicron=1.1.0=pyhd8ed1ab_1
- pyopenssl=19.1.0=py_1
- pyparsing=2.4.7=pyh9f0ad1d_0
- pyqt-impl=5.12.3=py38h7400c14_7
- pyqt5-sip=4.19.18=py38h709712a_7
- pyqt=5.12.3=py38h578d9bd_7
- pyqtchart=5.12=py38h7400c14_7
- pyqtgraph=0.11.1=pyhd3deb0d_0
- pyqtwebengine=5.12.1=py38h7400c14_7
- pyrsistent=0.17.3=py38h497a2fe_2
- pyrxp=2.1.0=py38h516909a_1000
- pysocks=1.7.1=py38h578d9bd_3
- pytables=3.6.1=py38hc386592_3
- pytest-forked=1.3.0=pyhd3deb0d_0
- pytest-mock=3.1.0=py_0
- pytest-runner=5.2=py_0
- pytest-socket=0.3.3=py_0
- pytest-xdist=1.32.0=pyh9f0ad1d_0
- pytest=5.3.5=py38h32f6830_2
- pythia8=8.244=py38h709712a_2
- python-avahi=0.7=py38h1a9c813_1
- python-confluent-kafka=1.3.0=py38h1e0a361_2
- python-dateutil=2.8.1=py_0
- python-framel=8.41.1=py38h5c078b8_0
- python-htcondor=8.9.11=py38h09861fb_2
- python-lal=7.1.2=fftw_py38h5e0d82a_100
- python-lalburst=1.5.8=py38h55b2093_0
- python-lalframe=1.5.4=py38h5c078b8_0
- python-lalinference=2.0.7=py38h5c078b8_0
- python-lalinspiral=2.0.2=py38h5c078b8_0
- python-lalmetaio=2.0.2=py38h5c078b8_0
- python-lalpulsar=3.0.1=py38h5c078b8_0
- python-lalsimulation=2.5.1=py38h5c078b8_0
- python-ldas-tools-al=2.6.7=py38hc9558a2_1
- python-ldas-tools-diskcacheapi=2.6.8=py38hc9558a2_0
- python-ldas-tools-frameapi=2.6.8=py38hc9558a2_0
- python-ldas-tools-framecpp=2.6.9=py38hc5bc63f_2
- python-ldas-tools-ldasgen=2.6.7=py38hc9558a2_0
- python-ligo-lw=1.6.0=py38h1e0a361_2
- python-nds2-client=0.16.8=py38hc5bc63f_0
- python-pegasus-wms=4.9.2=py_0
- python-xxhash=2.0.0=py38h497a2fe_1
- python=3.8.6=hffdb5ce_5_cpython
- python_abi=3.8=1_cp38
- pytz=2021.1=pyhd8ed1ab_0
- pyyaml=5.3.1=py38h7b6447c_0
- pyzmq=22.0.3=py38h2035c66_1
- qt=5.12.9=hda022c4_4
- qtpy=1.9.0=py_0
- readline=8.0=he28a2e2_2
- redis-py=3.4.1=py_0
- regex=2020.11.13=py38h497a2fe_1
- reproject=0.7.1=py38h5c078b8_1
- requests-ecp=0.2.1=py_0
- requests-gracedb=0.1.3=py_0
- requests-kerberos=0.12.0=py38h578d9bd_2
- requests-mock=1.7.0=py_0
- requests=2.23.0=pyh8c360ce_2
- retrying=1.3.3=py_2
- rhash=1.4.1=h7f98852_0
- rift=0.0.15.5=py38h578d9bd_0
- root-binaries=6.22.6=py38hd0710c8_1
- root-dependencies=6.22.6=py38hd0710c8_1
- root=6.22.6=py38hd0710c8_1
- root_base=6.22.6=py38hd214d3e_1
- root_numpy=4.8.0=py38h02e4990_10
- safe-netrc=1.0.0=py_0
- scikit-learn=0.22.2.post1=py38hcdab131_0
- scipy=1.5.3=py38hb2138dd_0
- seaborn-base=0.11.0=pyhd8ed1ab_1
- seaborn=0.11.0=ha770c72_1
- send2trash=1.5.0=py_0
- sentry-sdk=0.14.3=pyh9f0ad1d_1
- service_identity=18.1.0=py_0
- setproctitle=1.2.2=py38h497a2fe_0
- setuptools=46.1.3=py38h32f6830_0
- shapely=1.6.4=py38hec07ddf_1006
- six=1.14.0=py_1
- sleekxmpp=1.3.3=py_0
- smmap=3.0.5=pyh44b312d_0
- soupsieve=2.0.1=py_1
- spinners=0.0.24=pyh9f0ad1d_0
- sqlalchemy=1.3.16=py38h1e0a361_0
- sqlite=3.34.0=h74cdb3f_0
- statsmodels=0.12.2=py38h5c078b8_0
- swig=3.0.12=hf484d3e_1003
- sysroot_linux-64=2.12=h77966d4_13
- tbb-devel=2020.2=h4bd325d_4
- tbb=2020.2=h4bd325d_4
- termcolor=1.1.0=py_2
- terminado=0.9.2=py38h578d9bd_0
- testpath=0.4.4=py_0
- tk=8.6.10=h21135ba_1
- tmux=3.1=h1c4e50f_0
- toml=0.10.2=pyhd8ed1ab_0
- tornado=6.1=py38h497a2fe_1
- tqdm=4.45.0=pyh9f0ad1d_1
- traitlets=5.0.5=py_0
- twisted=20.3.0=py38h497a2fe_2
- typed-ast=1.4.2=py38h497a2fe_0
- uproot-base=3.11.7=py38h32f6830_0
- uproot-methods=0.9.2=pyhd8ed1ab_0
- uproot=3.11.7=py38h32f6830_0
- urllib3=1.25.8=py38h32f6830_1
- vdt=0.4.3=h9c3ff4c_0
- vine=1.3.0=py_0
- virtualenv=16.7.5=py_0
- voeventlib=1.2=py_0
- voms=2.1.0rc0=h2c113ba_1
- wcwidth=0.2.5=pyh9f0ad1d_2
- webencodings=0.5.1=py_1
- werkzeug=0.16.1=py_0
- wget=1.20.1=h22169c7_0
- wheel=0.34.2=py_1
- wrapt=1.12.1=py38h497a2fe_3
- xorg-fixesproto=5.0=h14c3975_1002
- xorg-kbproto=1.0.7=h7f98852_1002
- xorg-libice=1.0.10=h7f98852_0
- xorg-libsm=1.2.3=hd9c2040_1000
- xorg-libx11=1.6.12=h516909a_0
- xorg-libxau=1.0.9=h7f98852_0
- xorg-libxcursor=1.2.0=h516909a_0
- xorg-libxdmcp=1.1.3=h7f98852_0
- xorg-libxext=1.3.4=h516909a_0
- xorg-libxfixes=5.0.3=h516909a_1004
- xorg-libxft=2.3.3=h71203ad_0
- xorg-libxpm=3.5.13=h516909a_0
- xorg-libxrender=0.9.10=h516909a_1002
- xorg-libxt=1.1.5=h516909a_1003
- xorg-renderproto=0.11.1=h7f98852_1002
- xorg-xextproto=7.3.0=h7f98852_1002
- xorg-xproto=7.0.31=h7f98852_1007
- xrootd=5.1.0=py38h5962cf3_0
- xxhash=0.8.0=h7f98852_3
- xz=5.2.5=h516909a_1
- yaml=0.1.7=h14c3975_1001
- zeromq=4.3.4=h9c3ff4c_0
- zipp=3.1.0=py_0
- zlib=1.2.11=h516909a_1010
- zope.interface=5.1.0=py38h1e0a361_0
- zstandard=0.15.2=py38h497a2fe_0
- zstd=1.4.9=ha95c52a_0
name: igwn-py38
